apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  labels:
    app: flask-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: us-central1-docker.pkg.dev/GOOGLE_CLOUD_PROJECT/gke-demo-repository/flask-demo:COMMIT_SHA
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: flask-demo
spec:
  selector:
    app: flask-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer